import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import React, { Suspense } from "react";
import { ProgressBar } from "@lexz451/next-nprogress";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import "@/styles/globals.css";
import Screen from "@/components/desktop/screen";
import { roboto, SegoeUIDisplayFont, SegoIconFont } from "@/font";
import { LoadingHelper } from "@/lib/loading/loading-comps";
import { ThemeHelper } from "@/hooks/useTheme";
import SettingInit from "@/lib/Setting/setting-init";
let ShadcnThemeEditor: any;
if (process.env.NODE_ENV === "development") {
    import("shadcn-theme-editor").then((module) => {
        ShadcnThemeEditor = module.default; // or module, depending on the module's export
    });
} else {
    // eslint-disable-next-line react/display-name
    ShadcnThemeEditor = () => null;
}

export const metadata: Metadata = {
    title: "Fluent UI",
    description: "Generated by Immi",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <Body>
                <Screen>{children}</Screen>
            </Body>
        </html>
    );
}

function Body({ children }: { children: React.ReactNode }) {
    return (
        <body
            className={`!pointer-events-auto fixed min-h-screen ${roboto.className} ${SegoIconFont.variable} ${SegoeUIDisplayFont.variable}`}
            // style={{fontFamily: roboto.style.fontFamily}}
        >
            <Suspense fallback={<>Loading.............</>}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Suspense fallback={true}>
                        <ProgressBar
                            color="#333"
                            height="2px"
                            options={{
                                showSpinner: false,
                            }}
                        />
                        <LoadingHelper />
                    </Suspense>
                    {children}
                    <ShadcnThemeEditor />
                    <TailwindIndicator />
                    <ThemeHelper />
                    <SettingInit />
                </ThemeProvider>
                <button id="button" className="size-0 opacity-0" />
            </Suspense>
        </body>
    );
}
